### PR TITLE
Allow {{.}} to appear on the top level

### PR DESCRIPTION
**Pull request by arjan**
This enables support for lists and binary values as the main context value instead of just maps / proplists:

```erlang
bbmustache:render(<<"hello {{.}}">>, <<"world">>).
```

### CODE REVIEW

**Comment by soranoba** [comment]
Thank you for contribute =)
Researching other language implementations, I am positive about this feature.
However, the PR needs many corrections that are missing...
For example, many type spec needs to change.

So, I will consider it once.

**Comment by arjan** [comment]
Can you point me in the right direction? Running `./rebar3 dialyzer` on the project does not seem to do much (don't see any typespec errors..) By the way in the last commit I changed back the return value of `check_data_type` so it still returns the same (true | false | maybe).

**Comment by soranoba** [comment]
> Can you point me in the right direction?

I may add a commit by me.
If the PR need only a small fix, I will point out the part that needs fixing.

I will do the work at next week. Please wait some days.

> Running ./rebar3 dialyzer on the project does not seem to do much (don't see any typespec errors..) 

Yh.
I know the problem, but this is a problem with dialyzer, so it's difficult to solve it without doing ad-hoc things.
To give a brief overview, dialyzer will check by writing code that calls exported functions of bbmustache.

> By the way in the last commit I changed back the return value of check_data_type so it still returns the same (true | false | maybe).

There is no problem there.

```diff
--spec render(binary(), data()) -> binary().
+-spec render(binary(), data_value()) -> binary().
```

It is necessary to make such corrections, but the impact is widespread and may not have been just a type problem.
I have a responsibility to confirm this.

**Comment by soranoba** [comment]
@arjan 

I challenge to corresponded correctly, and the diff was over 100 more lines.
I want to respect your contributions, but It was not realistic to instruct you to fix all this.
For result, I push other PR #40  included your commits.
(I deleted a commit https://github.com/soranoba/bbmustache/pull/38/commits/86bee09b7150ada81a3dc48aed86d5edd0bdc980 because it was occur to confuse)

If it is an unwanted result, you can offer to me.

**Comment by soranoba** [comment]
Solved with #40

**Pull request closed without merging**
