### PR TITLE
Use funs as data

### LINKED ISSUE #36: Use a fun as Data
Currently one can supply a proplist or a map as `Data` argument to `render` function. However it may be useful to use a custom function as well. This should be very easy to implement: just add a `when is_function` clause to `find_data/2`... 

I can create a PR unless anyone got objections.

### PR DESCRIPTION
**Pull request by Vagabond**
Fixes #36

This is a rebase in case anyone else still wants this feature.

### CODE REVIEW

**Comment by yordis** [comment]
@soranoba is there any way we could get this?

**Comment by soranoba** [comment]
Please fork [the branch](https://github.com/helium/bbmustache/tree/data-fun)
Official support is no planned now.

**Comment by yordis** [comment]
> Official support is no planned now.

@soranoba what do you mean? Does that mean you will no support this?

Sorry, I didn't understand.

**Comment by yordis** [comment]
Should this PR be close if that is the case?

**Comment by soranoba** [comment]
I'm no plans to merge this PR, because it affects other specifications.
It seems to make you expect, so I will close.

**Pull request closed without merging**
