### PR TITLE
Custom Default Value Function Support

### PR DESCRIPTION
**Pull request by xmppjingle**
Example of usage:

```

custom_default_test_() ->
    [
     {"simple default replacement",
      fun() ->
              ?assertEqual(<<"test, test">>,
                           bbmustache:render(<<"{{i}}, {{f}}">>,
                                             [], [{default_value, fun(_X) -> <<"test">> end}]))
      end},
     {"default modifier",
      fun() ->
              ?assertEqual(<<"&lt;Jedi&gt;">>,
                           bbmustache:render(<<"{{Jedi}}">>,
                                             [], [{default_value, fun(X) -> "<" ++ X ++ ">" end}]))
      end}
    ].

### CODE REVIEW

**Comment by soranoba** [comment]
First, I think that few people want to set the same default value for all variables.
Second, it is possible to set a static default value for each variable.

e.g.
```
{{#name}}{{name}}{{/name}}{{^name}}Alice{{/name}}
```

Third, if you need a dynamic default value, you can do it by editing the map you pass.

---

I think this feature is unnecessary so ​I close it

**Comment by xmppjingle** [comment]
The issue/problem that it solves:
* Without updating documents to accommodate the notation, change the 'hardcoded' <<>> default that we have at the moment.
* When you have multiple layers of mustache processors, you may not want to replace {{KEY}}, and skip it. For reference I use a default, that reconstruct the {{KEY}}. fun(X) -> "{{" ++ X ++ "}}" end. 
* It is not very uncommon that we have pipelines that each layer process mustaches based on availability. bbmustache cannot be used as part of the chain. 

Anyways, thanks for great and fast software.

**Comment by xmppjingle** [comment]
@soranoba I also thought about extending the custom serialization function to support 2 args 'f(Key, Value)' so that it could be handled at the point instead of a new default processor. Not sure if that is better though.

**Comment by soranoba** [comment]
Hi @xmppjingle 

I'm sorry to be late. And, I apologize to you.
I considered this feature and tried to implement it, but I wasn't satisfied with it.

Mustache has a specification called context.

```erl
1> bbmustache:render(<<"{{#a}}{{b}}{{/a}}">>, #{"a" => #{}, "b" => "B"}).
<<"B">>
```

At this time, it is searched in the following order to find the value of "b".
1. `#{}` does not have `b`.
2. `#{"a" => #{}, "b" => "B"}` has `b`

If it makes the default values available, it will need the information for these steps.
I think that it allows delegation of data retrieval using a behavior, but context and data retrieval are closely related, and cutting them out seemed to be very inconvenient.

Therefore, it was concluded that it is difficult (it means high cost) to put this function.
I'm sorry I didn't meet your expectations.

Thanks.

**Comment by xmppjingle** [comment]
No problem.

The optimal implementation would be indeed at the very end of the chain. To avoid removing mustache declarations to which the context/layer did not have a value for.
The issue I see is that simple removing "{{Key}}" very often is not desired, due to loss of information.

I ended up unfortunately using my forked version, although not ideal, it did allow me to use bbmustache in layered services on production. 

Keep the good work 

Regards,

**Pull request closed without merging**
